<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAwesomeWordsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('awesome_words', function (Blueprint $table) {
            $table->increments('id');
            $table->string('word', 11)->nullable();
            $table->string('name', 11)->nullable();
            $table->string('pirate_name', 11)->nullable();
            $table->integer('hits')->nullable()->default(0);
            $table->nullableTimestamps();

            $table->unique('word', 'word');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('awesome_words');
    }
}
